name = "asonpeikoff"
main = "src/index.js"
compatibility_date = "2023-12-01"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css"]
fallthrough = true

[env.production]
routes = [
  { pattern = "asonpeikoff.com", zone_name = "asonpeikoff.com" }
]
